name: PixelmonLegend
version: '${version}'
main: io.github.hoya.pixelmonlegend.PixelmonLegend
commands:
  message:
    description: "about message system"
  custom-item:
    description: "about custom-item system"
  designation:
    description: "about designation system"
  economy:
    description: "about economy system"
  random-box:
    description: "about random-box system"
  regen-block:
    description: "about regen-block system"
  give-all:
    description: "about utility system"
    aliases:
      - ga
      - 전체지급
  torch:
    description: "about utility system"
    aliases:
      - t
      - 횃불
      - 토치
  basic-item:
    description: "about utility system"
    aliases:
      - bi
      - 기본템
